### ISSUE TITLE
reading input from csv for a subject

### ISSUE THREAD

**Issue by 99003554** [amanajaykalaskar/Mark_Analysis#3] opened 2021-02-28 17:11 UTC
Anomalous backslash in string: '\C'. String constant might be missing an r prefix.
	"startLineNumber": 60,
	"endLineNumber": 60,

**Comment by 99003521** [comment] 2021-02-28 20:04
Thanks Ragul for noticing the error. The issue is fixed now.

**Comment by 99003521** [comment] 2021-02-28 20:04
Thanks Ragul for noticing the error. The issue is fixed now.

**Closed as completed by 99003521** 2021-02-28 20:04 UTC
